// Package all imports all vulgar modules to trigger their init() registration.
// Import this package with a blank identifier to enable all modules:
//
//	import _ "github.com/zepzeper/vulgar/internal/modules/all"
package all

import (
	// Core modules (no prefix)
	_ "github.com/zepzeper/vulgar/internal/modules/core/crypto"
	_ "github.com/zepzeper/vulgar/internal/modules/core/env"
	_ "github.com/zepzeper/vulgar/internal/modules/core/fs"
	_ "github.com/zepzeper/vulgar/internal/modules/core/http"
	_ "github.com/zepzeper/vulgar/internal/modules/core/json"
	_ "github.com/zepzeper/vulgar/internal/modules/core/log"
	_ "github.com/zepzeper/vulgar/internal/modules/core/path"
	_ "github.com/zepzeper/vulgar/internal/modules/core/time"
	_ "github.com/zepzeper/vulgar/internal/modules/core/uuid"

	// Standard library modules (stdlib.*)
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/cache"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/compress/gzip"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/compress/tar"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/compress/zip"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/cron"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/csv"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/event"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/filewatch"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/health"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/html"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/jwt"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/mathx"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/metrics"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/osinfo"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/parallel"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/process"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/queue"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/regex"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/retry"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/secrets"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/shell"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/strings"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/template"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/timer"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/trace"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/url"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/validator"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/workflow"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/xml"
	_ "github.com/zepzeper/vulgar/internal/modules/stdlib/yaml"

	// Integration modules (integrations.*)
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/airtable"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/codeberg"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/dns"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/docker"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/ftp"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/github"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/gitlab"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/google/gcalendar"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/google/gdrive"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/google/gsheets"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/graphql"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/k8s"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/kafka"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/mongodb"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/nats"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/notify/discord"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/notify/slack"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/notify/telegram"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/notion"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/postgres"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/rabbitmq"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/redis"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/s3"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/smtp"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/sqlite"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/ssh"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/stripe"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/twilio"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/webhook"
	_ "github.com/zepzeper/vulgar/internal/modules/integrations/websocket"

	// AI modules (ai.*)
	_ "github.com/zepzeper/vulgar/internal/modules/ai/anthropic"
	_ "github.com/zepzeper/vulgar/internal/modules/ai/huggingface"
	_ "github.com/zepzeper/vulgar/internal/modules/ai/localai"
	_ "github.com/zepzeper/vulgar/internal/modules/ai/ollama"
	_ "github.com/zepzeper/vulgar/internal/modules/ai/openai"
)
